services:
  api:
    build: .
    command: "poetry run python3 /api/manage.py runserver"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/api
  worker:
    build: .
    command: "poetry run celery -A go_capture.tasks worker"
    depends_on:
      - broker
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672
    env_file:
      - .env
    volumes:
      - .:/api
  broker:
    image: rabbitmq
