services:
  api:
    command: "poetry run gunicorn go_capture.wsgi:application --bind 0.0.0.0:8000 -t 60"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672
    env_file:
      - env/prod.env
    image: ${image}:${tag}
    ports:
      - 8000:8000
    volumes:
      - media:/api/media
  worker:
    command: "poetry run celery -A go_capture.tasks worker"
    depends_on:
      - broker
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672
      - CELERY_RESULT_BACKEND=rpc
    env_file:
      - env/prod.env
    image: ${image}:${tag}
    volumes:
      - media:/api/media
  broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $MEDIA_ROOT
