services:
  api:
    image: ${account_id}.dkr.ecr.us-west-1.amazonaws.com/go-capture:${image_hash}
    env_file:
      - .env
    ports:
      - 8000:8000
  broker:
    image: rabbitmq
    ports:
      - 5672:5672
