### health check
GET {{protocol}}{{host}}:{{port}}/health_check/

### POST image
POST {{protocol}}{{host}}:{{port}}/capture/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="board.jpg"
Content-Type: image/jpeg

< ./images/whole_board/20220305_144247.jpg
--WebAppBoundary--

### POST image with worker queue
POST {{protocol}}{{host}}:{{port}}/capture_async/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fcm_registration_token"
Content-Type: text/plain

foobar

--WebAppBoundary
Content-Disposition: form-data; name="to_play"
Content-Type: text/plain

W

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="board.jpg"
Content-Type: image/jpeg

< ./images/whole_board/20220305_144247.jpg
--WebAppBoundary--
