AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  BetaDeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: BetaDeployUser
      Policies:
        - !Ref EcrDeployPolicy
  EcrDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EcrDeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: "*"
