Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: go-capture
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep newest",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": "expire"
              }
            ]
          }
Outputs:
  GoCaptureRepository:
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryArn'
