Parameters:
  GithubOrg:
    Type: String
  RepositoryName:
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String

Resources:
  GithubRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubOrg}/${RepositoryName}:*
      Path: /gocapture/
      Policies:
        - PolicyName: CloudFormationPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": cloudformation:DescribeStacks,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": cloudformation:CreateChangeSet,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": cloudformation:DescribeChangeSet,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": cloudformation:ExecuteChangeSet,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": cloudformation:CreateStack,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": cloudformation:DeleteChangeSet,
                "Resource": "*"
              },
            ]
          }
        - PolicyName: IamPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": iam:UpdateAssumeRolePolicy,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": iam:GetRole,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": iam:PutRoleRole,
                "Resource": "*"
              },
            ]
          }
        - PolicyName: EcrPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": ecr:CreateRepository,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": ecr:GetAuthorizationToken,
                "Resource": "*"
              },
              {
                "Effect": Allow,
                "Action": ecr:PutImage,
                "Resource": "*"
              },
            ]
          }

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt GithubRole.Arn
