Parameters:
  Repository:
    Type: String

Resources:
  GithubRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${Repository}:*
      Path: /gocapture/
      Policies:
        - PolicyName: CloudFormationPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": [
                  cloudformation:CreateChangeSet,
                  cloudformation:CreateStack,
                  cloudformation:DeleteChangeSet,
                  cloudformation:DescribeChangeSet,
                  cloudformation:DescribeStacks,
                  cloudformation:ExecuteChangeSet,
                ],
                "Resource": "*"
              },
            ]
          }
        - PolicyName: IamPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": [
                  iam:CreateUser,
                  iam:DeleteUser,
                  iam:DeleteUserPolicy,
                  iam:GetRole,
                  iam:GetUser,
                  iam:ListAccessKeys,
                  iam:PutRolePolicy,
                  iam:PutRoleRole,
                  iam:PutUserPolicy,
                  iam:UpdateAssumeRolePolicy,
                ],
                "Resource": "*"
              },
            ]
          }
        - PolicyName: EcrPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": [
                  ecr:BatchCheckLayerAvailability,
                  ecr:BatchGetImage,
                  ecr:CompleteLayerUpload,
                  ecr:CreateRepository,
                  ecr:GetAuthorizationToken,
                  ecr:GetDownloadUrlForLayer,
                  ecr:InitiateLayerUpload,
                  ecr:PutImage,
                  ecr:UploadLayerPart
                ],
                "Resource": "*"
              },
            ]
          }

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt GithubRole.Arn
