name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::200049542062:role/go_capture/GithubRole
          aws-region: us-west-1

      - name: Deploy ECS Cluster
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GoCaptureECSCluster
          template: cloud-formation/ecs.yaml
          no-fail-on-empty-changeset: 1
