name: Users
on:
  push:

jobs:
  deploy_users:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::200049542062:role/gocapture/GithubRole
          aws-region: us-west-1

      - name: Beta Deploy User
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GoCaptureBetaDeployUser
          template: cloud-formation/beta-deploy-user.yaml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: 1
